nohup python exptau_globalsearch.py --dataset texas --tau 0.1 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset texas --tau 0.2 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset texas --tau 0.3 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset texas --tau 0.4 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset texas --tau 0.5 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset texas --tau 0.6 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset texas --tau 0.7 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset texas --tau 0.8 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset texas --tau 0.9 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset cornell --tau 0.1 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset cornell --tau 0.2 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset cornell --tau 0.3 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset cornell --tau 0.4 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset cornell --tau 0.5 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset cornell --tau 0.6 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset cornell --tau 0.7 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset cornell --tau 0.8 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset cornell --tau 0.9 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset wisconsin --tau 0.1 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset wisconsin --tau 0.2 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset wisconsin --tau 0.3 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset wisconsin --tau 0.4 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset wisconsin --tau 0.5 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset wisconsin --tau 0.6 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset wisconsin --tau 0.7 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset wisconsin --tau 0.8 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset wisconsin --tau 0.9 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset cora --tau 0.1 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset cora --tau 0.2 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset cora --tau 0.3 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset cora --tau 0.4 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset cora --tau 0.5 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset cora --tau 0.6 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset cora --tau 0.7 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset cora --tau 0.8 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset cora --tau 0.9 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset citeseer --tau 0.1 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset citeseer --tau 0.2 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset citeseer --tau 0.3 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset citeseer --tau 0.4 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset citeseer --tau 0.5 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset citeseer --tau 0.6 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset citeseer --tau 0.7 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset citeseer --tau 0.8 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset citeseer --tau 0.9 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset photo --tau 0.1 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset photo --tau 0.2 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset photo --tau 0.3 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset photo --tau 0.4 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset photo --tau 0.5 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset photo --tau 0.6 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset photo --tau 0.7 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset photo --tau 0.8 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset photo --tau 0.9 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset dblp --tau 0.1 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset dblp --tau 0.2 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset dblp --tau 0.3 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset dblp --tau 0.4 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset dblp --tau 0.5 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset dblp --tau 0.6 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset dblp --tau 0.7 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset dblp --tau 0.8 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset dblp --tau 0.9 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset cs --tau 0.1 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset cs --tau 0.2 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset cs --tau 0.3 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset cs --tau 0.4 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset cs --tau 0.5 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset cs --tau 0.6 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset cs --tau 0.7 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset cs --tau 0.8 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset cs --tau 0.9 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset physics --tau 0.1 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset physics --tau 0.2 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset physics --tau 0.3 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset physics --tau 0.4 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset physics --tau 0.5 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset physics --tau 0.6 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset physics --tau 0.7 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset physics --tau 0.8 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset physics --tau 0.9 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset reddit  --tau 0.1 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset reddit  --tau 0.2 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset reddit  --tau 0.3 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset reddit  --tau 0.4 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset reddit  --tau 0.5 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset reddit  --tau 0.6 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset reddit  --tau 0.7 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset reddit  --tau 0.8 >> ./logs/exp_tau_search.txt 2>&1 &&
python exptau_globalsearch.py --dataset reddit  --tau 0.8 >> ./logs/exp_tau_search.txt 2>&1 &