nohup python expsim_globalsearch.py --dataset texas --similarity_method cosine >> ./logs/exp_similarity_method_search.txt 2>&1 &&
python expsim_globalsearch.py --dataset texas --similarity_method l1 >> ./logs/exp_similarity_method_search.txt 2>&1 &&
python expsim_globalsearch.py --dataset texas --similarity_method l2 >> ./logs/exp_similarity_method_search.txt 2>&1 &&
python expsim_globalsearch.py --dataset cornell --similarity_method cosine >> ./logs/exp_similarity_method_search.txt 2>&1 &&
python expsim_globalsearch.py --dataset cornell --similarity_method l1 >> ./logs/exp_similarity_method_search.txt 2>&1 &&
python expsim_globalsearch.py --dataset cornell --similarity_method l2 >> ./logs/exp_similarity_method_search.txt 2>&1 &&
python expsim_globalsearch.py --dataset wisconsin --similarity_method cosine >> ./logs/exp_similarity_method_search.txt 2>&1 &&
python expsim_globalsearch.py --dataset wisconsin --similarity_method l1 >> ./logs/exp_similarity_method_search.txt 2>&1 &&
python expsim_globalsearch.py --dataset wisconsin --similarity_method l2 >> ./logs/exp_similarity_method_search.txt 2>&1 &&
python expsim_globalsearch.py --dataset cora --similarity_method cosine >> ./logs/exp_similarity_method_search.txt 2>&1 &&
python expsim_globalsearch.py --dataset cora --similarity_method l1 >> ./logs/exp_similarity_method_search.txt 2>&1 &&
python expsim_globalsearch.py --dataset cora --similarity_method l2 >> ./logs/exp_similarity_method_search.txt 2>&1 &&
python expsim_globalsearch.py --dataset citeseer --similarity_method cosine >> ./logs/exp_similarity_method_search.txt 2>&1 &&
python expsim_globalsearch.py --dataset citeseer --similarity_method l1 >> ./logs/exp_similarity_method_search.txt 2>&1 &&
python expsim_globalsearch.py --dataset citeseer --similarity_method l2 >> ./logs/exp_similarity_method_search.txt 2>&1 &&
python expsim_globalsearch.py --dataset photo --similarity_method cosine >> ./logs/exp_similarity_method_search.txt 2>&1 &&
python expsim_globalsearch.py --dataset photo --similarity_method l1 >> ./logs/exp_similarity_method_search.txt 2>&1 &&
python expsim_globalsearch.py --dataset photo --similarity_method l2 >> ./logs/exp_similarity_method_search.txt 2>&1 &&
python expsim_globalsearch.py --dataset dblp --similarity_method cosine >> ./logs/exp_similarity_method_search.txt 2>&1 &&
python expsim_globalsearch.py --dataset dblp --similarity_method l1 >> ./logs/exp_similarity_method_search.txt 2>&1 &&
python expsim_globalsearch.py --dataset dblp --similarity_method l2 >> ./logs/exp_similarity_method_search.txt 2>&1 &&
python expsim_globalsearch.py --dataset cs --similarity_method cosine >> ./logs/exp_similarity_method_search.txt 2>&1 &&
python expsim_globalsearch.py --dataset cs --similarity_method l1 >> ./logs/exp_similarity_method_search.txt 2>&1 &&
python expsim_globalsearch.py --dataset cs --similarity_method l2 >> ./logs/exp_similarity_method_search.txt 2>&1 &&
python expsim_globalsearch.py --dataset physics --similarity_method cosine >> ./logs/exp_similarity_method_search.txt 2>&1 &&
python expsim_globalsearch.py --dataset physics --similarity_method l1 >> ./logs/exp_similarity_method_search.txt 2>&1 &&
python expsim_globalsearch.py --dataset physics --similarity_method l2 >> ./logs/exp_similarity_method_search.txt 2>&1 &&
python expsim_globalsearch.py --dataset reddit  --similarity_method cosine >> ./logs/exp_similarity_method_search.txt 2>&1 &&
python expsim_globalsearch.py --dataset reddit  --similarity_method l1 >> ./logs/exp_similarity_method_search.txt 2>&1 &&
python expsim_globalsearch.py --dataset reddit  --similarity_method l2 >> ./logs/exp_similarity_method_search.txt 2>&1 &