nohup python accuracy_globalsearch.py --dataset texas --embedding_tensor_name epoch050_texas >> ./logs/exp_epoch_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset texas --embedding_tensor_name epoch150_texas >> ./logs/exp_epoch_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset texas --embedding_tensor_name epoch200_texas >> ./logs/exp_epoch_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cornell --embedding_tensor_name epoch050_cornell >> ./logs/exp_epoch_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cornell --embedding_tensor_name epoch150_cornell >> ./logs/exp_epoch_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cornell --embedding_tensor_name epoch200_cornell >> ./logs/exp_epoch_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset wisconsin --embedding_tensor_name epoch050_wisconsin >> ./logs/exp_epoch_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset wisconsin --embedding_tensor_name epoch150_wisconsin >> ./logs/exp_epoch_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset wisconsin --embedding_tensor_name epoch200_wisconsin >> ./logs/exp_epoch_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cora --embedding_tensor_name epoch050_cora >> ./logs/exp_epoch_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cora --embedding_tensor_name epoch150_cora >> ./logs/exp_epoch_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cora --embedding_tensor_name epoch200_cora >> ./logs/exp_epoch_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset citeseer --embedding_tensor_name epoch050_citeseer >> ./logs/exp_epoch_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset citeseer --embedding_tensor_name epoch150_citeseer >> ./logs/exp_epoch_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset citeseer --embedding_tensor_name epoch200_citeseer >> ./logs/exp_epoch_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset photo --embedding_tensor_name epoch050_photo >> ./logs/exp_epoch_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset photo --embedding_tensor_name epoch150_photo >> ./logs/exp_epoch_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset photo --embedding_tensor_name epoch200_photo >> ./logs/exp_epoch_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset dblp --embedding_tensor_name epoch050_dblp >> ./logs/exp_epoch_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset dblp --embedding_tensor_name epoch150_dblp >> ./logs/exp_epoch_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset dblp --embedding_tensor_name epoch200_dblp >> ./logs/exp_epoch_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cs --embedding_tensor_name epoch050_cs >> ./logs/exp_epoch_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cs --embedding_tensor_name epoch150_cs >> ./logs/exp_epoch_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cs --embedding_tensor_name epoch200_cs >> ./logs/exp_epoch_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset physics --embedding_tensor_name epoch050_physics >> ./logs/exp_epoch_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset physics --embedding_tensor_name epoch150_physics >> ./logs/exp_epoch_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset physics --embedding_tensor_name epoch200_physics >> ./logs/exp_epoch_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset reddit  --embedding_tensor_name epoch050_reddit >> ./logs/exp_epoch_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset reddit  --embedding_tensor_name epoch150_reddit >> ./logs/exp_epoch_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset reddit  --embedding_tensor_name epoch200_reddit >> ./logs/exp_epoch_search.txt 2>&1 &