nohup python accuracy_globalsearch.py --dataset texas --embedding_tensor_name alpha001_texas >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset texas --embedding_tensor_name alpha030_texas >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset texas --embedding_tensor_name alpha050_texas >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset texas --embedding_tensor_name alpha070_texas >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset texas --embedding_tensor_name alpha090_texas >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cornell --embedding_tensor_name alpha001_cornell >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cornell --embedding_tensor_name alpha030_cornell >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cornell --embedding_tensor_name alpha050_cornell >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cornell --embedding_tensor_name alpha070_cornell >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cornell --embedding_tensor_name alpha090_cornell >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset wisconsin --embedding_tensor_name alpha001_wisconsin >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset wisconsin --embedding_tensor_name alpha030_wisconsin >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset wisconsin --embedding_tensor_name alpha050_wisconsin >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset wisconsin --embedding_tensor_name alpha070_wisconsin >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset wisconsin --embedding_tensor_name alpha090_wisconsin >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cora --embedding_tensor_name alpha001_cora >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cora --embedding_tensor_name alpha030_cora >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cora --embedding_tensor_name alpha050_cora >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cora --embedding_tensor_name alpha070_cora >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cora --embedding_tensor_name alpha090_cora >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset citeseer --embedding_tensor_name alpha001_citeseer >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset citeseer --embedding_tensor_name alpha030_citeseer >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset citeseer --embedding_tensor_name alpha050_citeseer >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset citeseer --embedding_tensor_name alpha070_citeseer >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset citeseer --embedding_tensor_name alpha090_citeseer >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset photo --embedding_tensor_name alpha001_photo >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset photo --embedding_tensor_name alpha030_photo >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset photo --embedding_tensor_name alpha050_photo >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset photo --embedding_tensor_name alpha070_photo >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset photo --embedding_tensor_name alpha090_photo >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset dblp --embedding_tensor_name alpha001_dblp >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset dblp --embedding_tensor_name alpha030_dblp >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset dblp --embedding_tensor_name alpha050_dblp >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset dblp --embedding_tensor_name alpha070_dblp >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset dblp --embedding_tensor_name alpha090_dblp >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cs --embedding_tensor_name alpha001_cs >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cs --embedding_tensor_name alpha030_cs >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cs --embedding_tensor_name alpha050_cs >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cs --embedding_tensor_name alpha070_cs >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cs --embedding_tensor_name alpha090_cs >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset physics --embedding_tensor_name alpha001_physics >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset physics --embedding_tensor_name alpha030_physics >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset physics --embedding_tensor_name alpha050_physics >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset physics --embedding_tensor_name alpha070_physics >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset physics --embedding_tensor_name alpha090_physics >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset reddit  --embedding_tensor_name alpha010_reddit >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset reddit  --embedding_tensor_name alpha030_reddit >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset reddit  --embedding_tensor_name alpha050_reddit >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset reddit  --embedding_tensor_name alpha070_reddit >> ./logs/exp_alpha_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset reddit  --embedding_tensor_name alpha090_reddit >> ./logs/exp_alpha_search.txt 2>&1 &