nohup python accuracy_globalsearch.py --dataset texas --embedding_tensor_name hop001_texas >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset texas --embedding_tensor_name hop002_texas >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset texas --embedding_tensor_name hop003_texas >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset texas --embedding_tensor_name hop004_texas >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset texas --embedding_tensor_name hop006_texas >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cornell --embedding_tensor_name hop001_cornell >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cornell --embedding_tensor_name hop002_cornell >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cornell --embedding_tensor_name hop003_cornell >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cornell --embedding_tensor_name hop004_cornell >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cornell --embedding_tensor_name hop006_cornell >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset wisconsin --embedding_tensor_name hop001_wisconsin >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset wisconsin --embedding_tensor_name hop002_wisconsin >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset wisconsin --embedding_tensor_name hop003_wisconsin >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset wisconsin --embedding_tensor_name hop004_wisconsin >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset wisconsin --embedding_tensor_name hop006_wisconsin >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cora --embedding_tensor_name hop001_cora >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cora --embedding_tensor_name hop002_cora >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cora --embedding_tensor_name hop003_cora >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cora --embedding_tensor_name hop004_cora >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cora --embedding_tensor_name hop006_cora >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset citeseer --embedding_tensor_name hop001_citeseer >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset citeseer --embedding_tensor_name hop002_citeseer >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset citeseer --embedding_tensor_name hop003_citeseer >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset citeseer --embedding_tensor_name hop004_citeseer >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset citeseer --embedding_tensor_name hop006_citeseer >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset photo --embedding_tensor_name hop001_photo >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset photo --embedding_tensor_name hop002_photo >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset photo --embedding_tensor_name hop003_photo >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset photo --embedding_tensor_name hop004_photo >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset photo --embedding_tensor_name hop006_photo >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset dblp --embedding_tensor_name hop001_dblp >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset dblp --embedding_tensor_name hop002_dblp >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset dblp --embedding_tensor_name hop003_dblp >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset dblp --embedding_tensor_name hop004_dblp >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset dblp --embedding_tensor_name hop006_dblp >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cs --embedding_tensor_name hop001_cs >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cs --embedding_tensor_name hop002_cs >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset cs --embedding_tensor_name hop003_cs >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset physics --embedding_tensor_name hop001_physics >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset physics --embedding_tensor_name hop002_physics >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset physics --embedding_tensor_name hop003_physics >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset physics --embedding_tensor_name hop004_physics >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset physics --embedding_tensor_name hop006_physics >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset reddit  --embedding_tensor_name hop001_reddit >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset reddit  --embedding_tensor_name hop002_reddit >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset reddit  --embedding_tensor_name hop003_reddit >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset reddit  --embedding_tensor_name hop004_reddit >> ./logs/exp_hop_search.txt 2>&1 &&
python accuracy_globalsearch.py --dataset reddit  --embedding_tensor_name hop006_reddit >> ./logs/exp_hop_search.txt 2>&1 &